---
- name: Create image server EC2 instance
  hosts: localhost
  gather_facts: false
  vars_files: aws_defaults.yml

  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
        image: "{{ aws_rhel_ami }}"
        instance_type: t2.micro
        monitoring: true
        # persistent network device with stable internal IP 10.29.162.239 (DNS internal-images.cockpit-project.org)
        network_interfaces: eni-0e1ad6012dbbfa1d9
        wait: true
        instance_tags:
          Name: cockpit-images
          ServiceOwner: FrontDoorSST
          ServiceName: FrontDoorCI
          ServiceComponent: Images
          ServicePhase: Prod
          AppCode: ARR-001
      register: ec2

#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.private_ip }}"
#        groupname: launched
#      loop: "{{ ec2.instances }}"

    - name: Attach or create cache volume
      ec2_vol:
        instance: "{{ item.id }}"
        name: cockpit-images
        region: "{{ aws_region }}"
        volume_size: 150
        tags:
          ServiceOwner: FrontDoorSST
          ServiceName: FrontDoorCI
          ServiceComponent: Images
          ServicePhase: Prod
          AppCode: ARR-001
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.private_ip }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

#- name: Configure instances
#  hosts: launched
#  gather_facts: true
#  roles:
