---
 - name: Clone secrets repository
   delegate_to: localhost
   run_once: yes
   become: false
   git:
     repo: git@gitlab.cee.redhat.com:front-door-ci-wranglers/ci-secrets.git
     # use a directory which is guaranteed to be on tmpfs
     dest: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets"
     depth: 1

 # copy module is waaaay to slow for recursive directory copy; only upload one tarball
 # we need to resolve symlinks for ../ca.pem due to how container --volumes work
 # also don't include unnecessary secrets, like the CA key or workflow secrets
 - name: Generate secrets archive
   delegate_to: localhost
   become: false
   run_once: yes
   shell: |
     tar -C $XDG_RUNTIME_DIR/ci-secrets  -hz --hard-dereference -c webhook s3-keys tasks > $XDG_RUNTIME_DIR/ci-secrets.tar.gz
